# Generated by Django 4.2.16 on 2025-10-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_rating_user_movie_idx_user_movie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_user_movie',
        ),
        migrations.RenameIndex(
            model_name='rating',
            new_name='idx_user_movie_rating',
            old_name='idx_user_movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_rating'),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie_rater_api.movie',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='movie_rater_api.rating',
        ),
    ]
